import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const code=ts.transpileModule(readFileSync(new URL('../src/experiment/engine.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const context={exports:{}};vm.runInNewContext(code,context);
const events=[];
const engine=new context.exports.ExperimentEngine({revealMode:'full',numLights:1,segmentDurationSec:4,redWaitSec:15,startMoney:100,moneyLossPerSec:2},{log:event=>events.push(event)});
engine.start(0);
engine.pressWalk(50);engine.pressWalk(75);
for(let t=100;t<=4200;t+=25)engine.tick(t);
assert.equal(engine.state.phase,'waiting_red');
engine.pressWalk(4250);
assert.equal(engine.state.phase,'moving_to_finish');
for(const t of [4275,4300,4325])engine.pressWalk(t);
const presses=events.filter(e=>e.event==='walk_press');
assert.equal(presses.length,6);
assert.deepEqual(presses.map(e=>e.phase),['moving','moving','waiting_red','moving_to_finish','moving_to_finish','moving_to_finish']);
assert.equal(events.filter(e=>e.event==='pass_light').length,1);
assert.equal(events.filter(e=>e.event==='violation').length,1);
assert.equal(engine.state.violations,1);
for(let t=4350;t<=8400;t+=25)engine.tick(t);
assert.equal(engine.state.phase,'finished');
assert.ok(presses.every((e,i)=>!i||e.nowMs>presses[i-1].nowMs));
console.log('PASS: repeated clicks recorded in all active phases; no repeated crossing or violation');